name : Deployment workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name : Get source code
        uses : actions/checkout@v3

      - name : Configure AWS credentials
        uses : aws-actions/configure-aws-credentials@v1
        with :
          aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region : us-east-1
      
      - name : Install depencies and Build the application
        run : |
          npm install
          npm run build

      - name : Deploy to s3 bucket
        run : |
          aws s3 sync dist/ s3://frontend-bucket-45600001/ --delete